# integration tests for nx ecosystem projects - scheduled or manual run for all suites
name: nx-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  schedule:
    - cron: "0 5 * * 1,3,5" # monday,wednesday,friday 5AM
  repository_dispatch:
    types: [ecosystem-ci]
  workflow_dispatch:
jobs:
  test-ecosystem:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - monodon-rust
          - nx-aws-lambda
          - nx-deno
          - nx-examples
          - nx-netlify
          - nx-nx-ignore
          - nx-remix
          - nx-rspack
          - nxext-svelte
          - nxext-solid
          - nxext-stencil
          - nxext-vue
          - nxext-capacitor
          - nxext-ionic-angular
          - nxext-ionic-react
          - qwik-nx
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        id: setup-node
      - uses: dtolnay/rust-toolchain@stable
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        id: setup-deno
        continue-on-error: true
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts
          ${{ matrix.suite }}
        id: ecosystem-ci-run
      - if: always()
        run: pnpm tsx slack-webhook.ts
        env:
          WORKFLOW_NAME: ci
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: always()
        run: pnpm tsx discord-webhook.ts
        env:
          WORKFLOW_NAME: ci
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
